version: "3"
services:
  ubuntu:
    container_name: build_ubuntu
    image: kabosu910/9cc:latest
    volumes:
      - ./9cc:/9cc
    working_dir: /9cc
    environment: 
      TZ: Asia/Tokyo
    platform: "linux/amd64"
    tty: true